### PR TITLE
Donor Neon Command Fix

### PR DESCRIPTION
**Pull request by happyman090**
Fixed donor neon command to modify all BaseParts instead of just Parts

I am aware that neon does not correctly create a neon effect in most instances because of meshes, but there isn't much that can be done about this ig

### CODE REVIEW

**Comment by AStranger1k** [comment]
Would a meshpart work?

It seems neon works fine on meshparts

**Comment by Awesomewebm** [comment]
> Would a meshpart work?
> 
> It seems neon works fine on meshparts

I think it doesn’t work if the mesh has a texture iirc

**Comment by AStranger1k** [comment]
> > Would a meshpart work?
> > It seems neon works fine on meshparts
> 
> I think it doesn’t work if the mesh has a texture iirc

A texture is not necessary

**Comment by happyman090** [comment]
> Would a meshpart work?
> 
> It seems neon works fine on meshparts

Doesn't seem to work on R15 characters

**Comment by Awesomewebm** [comment]
> > Would a meshpart work?
> 
> > 
> 
> > It seems neon works fine on meshparts
> 
> 
> 
> Doesn't seem to work on R15 character parts affected by clothing or any other texture

Doesn't work on RTHRO either, as those are meshes with material textures

**Pull request merged**
