### PR TITLE
Add option to force use MockDatastore

### PR DESCRIPTION
**Pull request by ccuser44**
Useful for testing or if you have a free admin game.

For example on free Admin games (or other games too) you never wan't any datastores to ever save.

### CODE REVIEW

**Comment by P3tray** [comment]
finally, mds.

**Review by P3tray — APPROVED** [review]
hot and works

**Comment by p7stol** [comment]
I have experienced this within a game I moderate as well. It carries across multiple games, as both of them use adonis and I haven't been able to keep or even remove admins since about 4 days ago.

**Comment by ccuser44** [comment]
> @Expertcoderz someone said that the DataStore was working fine until 4 days ago. Could this maybe have caused the issue somehow?
> 
> Because people that use :mod, it apparently doesn't save across the other servers. And any server, even new created ones.

No. Unless this `warn(":: Adonis :: Using MockDataStoreService instead of DataStoreService")` appears in the console. There is no other way the datastore could be local

**Comment by ccuser44** [comment]
It surely can't be this pull request. The only it could be this pull request if the settings `settings.LocalDatastore` is set to `true`

**Comment by ccuser44** [comment]
But there have been a lot of other recent pull requests that also affect the datastores & admin loading so it could have something to do with those

**Comment by karl-police** [comment]
> It surely can't be this pull request. The only way it could be this pull request would be if the settings `settings.LocalDatastore` is set to `true`.

what's the default value of the setting?

**Comment by karl-police** [comment]
> But there have been a lot of other recent pull requests that also affect the datastores & admin loading so it could have something to do with those

we need to find which one :shrug:

**Comment by karl-police** [comment]
disregard I am about to find the issue

it wasn't caused by this push request

**Pull request merged**
