### PR TITLE
Update Commands.lua

### PR DESCRIPTION
**Pull request by EnderUwU**
Added :joinserver to join a server using jobid.

### CODE REVIEW

**Comment by Sceleratis** [comment]
wish I noticed this before pushing the new update lmao

**Comment by EnderUwU** [comment]
yes

**Comment by TheLegendarySpark** [comment]
There's something wrong in his code:

```assert(args[1].."Argument missing or nil")```

**Comment by Sceleratis** [comment]
Will fix during merge

**Pull request merged**
