### PR TITLE
Update Server.lua

### PR DESCRIPTION
**Pull request by watameln**
"getmetatable" was duplicated on line 41 and 51.

### CODE REVIEW

**Comment by h0nzzz** [comment]
theres `setmetatable` and `getmetatable`

**Comment by watameln** [comment]
nono getmetatable on 2 different lines. so it was duplicated.

**Comment by watameln** [comment]
Oh I just noticed yes. How do i close the pull request?

**Comment by h0nzzz** [comment]
there should be a `close pull request` button somewhere

**Pull request closed without merging**
