### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by TheLegendarySpark**

### CODE REVIEW

**Review by NNickey — CHANGES_REQUESTED** [review]
Use https://developer.roblox.com/en-us/api-reference/lua-docs/os

os.time() instead as Roblox servers may have different timezones when using tick()
tick() is good for getting to the millisecond, joined data probably best to be with UTC timezone on all game servers.

**Comment by Sceleratis** [comment]
oh also model files should use rbxmx from now on

**Comment by TheLegendarySpark** [comment]
> oh my god it hates you lol

Totally. Btw, the new window fixed the issue with Window not triggering ``OnClose`` function after the user pressed the close button.

**Comment by TheLegendarySpark** [comment]
I also ensured process RateLimit doesn't keep blocking incoming remotes. This is to fix issues with clients in Adonis attempting to run remote via command bar and other components.

**Comment by Sceleratis** [comment]
it still hates you lmao

**Comment by Sceleratis** [comment]
(tho probably more my fault this time)

**Comment by Sceleratis** [comment]
I'm thinking retry with the models removed or converted to rbxmx

**Pull request closed without merging**
