### PR TITLE
Update Anti.lua

### PR DESCRIPTION
**Pull request by L8X**
- Made inappropriate animation playing kick players (why were we not punishing them for it???)

- Decreased client timeout limit to 60 seconds (1 minute) (5 minutes is definitely too long Scel)

### CODE REVIEW

**Comment by LolloDev5123** [comment]
1. Too casual PR description thank you
2. You have re-implemented/undone the changes that were required to mostly prevent players from getting kicked accidentally, and you can't kick a player for an inappropriate animation. What if it's being used appropriately?

**Comment by GalacticInspired** [comment]
this is bad

**Comment by ccuser44** [comment]
> * Made inappropriate animation playing kick players (why were we not punishing them for it???)

There is an extremely small minority of very old games that use the animation. The current patch only stops other players from seeing it and displays a quick notification, which is adaquate and doesn't cause issues.



> * Decreased client timeout limit to 60 seconds (1 minute) (5 minutes is definitely too long Scel)

It's possible for the Roblox events to be throttled over a minute in very laggy situations. 5 minutes is sufficient but 1 minute has caused issues in the past.

**Review by ccuser44 — CHANGES_REQUESTED** [review]
Changing these will definetly lead to false flags.

**Pull request closed without merging**
