### PR TITLE
Fixed my log detectection

### PR DESCRIPTION
**Pull request by ccuser44**
I forgot to change "string" to "EnumItem" and thats why it was detecting.
 I̶ ̶w̶i̶l̶l̶ ̶s̶t̶i̶l̶l̶ ̶t̶e̶s̶t̶ ̶t̶h̶i̶s̶ ̶t̶h̶o̶u̶g̶h̶ ̶t̶h̶a̶t̶ ̶i̶t̶ ̶w̶o̶r̶k̶s̶. Yep it works now

### CODE REVIEW

**Comment by ccuser44** [comment]
Ok fixed it.

However:
> Unreliable Behavior
> This may have changing, unexpected or unreliable behavior depending on how the game engine logs things. It should not be > relied upon for any important game logic.

Roblox says not to rely on the behavior of the log thing but idk we can rely on atleast for now

**Comment by ccuser44** [comment]
Anyways I fixed the bug where it misdetected.

It was because I forgot to type "EnumItem" and instead typed "string"

And I also mispelled "timestamp" as "timeStamp"

**Comment by Sceleratis** [comment]
Welp apparently this was kicking people in private servers.... so uh I'm thinking back to the drawing board a bit. Re-disabled.

**Comment by ccuser44** [comment]
what? that shouldnt be possible.

**Comment by ccuser44** [comment]
> Welp apparently this was kicking people in private servers (for Bypass Detected, right above the log size check).... so uh I'm thinking back to the drawing board a bit. Re-disabled.

ok. umm do you have any information on this. and are you sure it was that check?

**Comment by ccuser44** [comment]
hmm.. only in private servers? was it all private servers or just certain ones

**Comment by Sceleratis** [comment]
> hmm.. only in private servers? was it all private servers or just certain ones

No information other than it was mass kicking in vip/private servers. I assume most of them, enough to where devforum posts started appearing about it. No logs or anything, unfortunately.

**Comment by ccuser44** [comment]
> hmm.. only in private servers? was it all private servers or just certain ones
> 
> 
> No information other than it was mass kicking in vip/private servers. I assume most of them, enough to where devforum posts started appearing about it. No logs or anything, unfortunately.


sorry i didn't known it would cause such an issue. The code seems 100% fine and I tested it multiple times and it worked properly

**Comment by ccuser44** [comment]
I need to investigate this when I cab

**Pull request merged**
