### PR TITLE
Update Commands.lua

### PR DESCRIPTION
**Pull request by EnderUwU**
added :custommessage :cm bassicaly :sm but you can chanche upper message too

### CODE REVIEW

**Review by Sceleratis — CHANGES_REQUESTED** [review]
Index has a typo pls fix

**Comment by pbstFusion** [comment]
**_COUGH_**

**Comment by EnderUwU** [comment]
> Index has a typo pls fix

where

**Comment by Sceleratis** [comment]
"CustommMessage"

**Comment by EnderUwU** [comment]
oh didnt notice that

**Comment by EnderUwU** [comment]
done lol

**Pull request merged**
