### PR TITLE
Windows XP Theme

### PR DESCRIPTION
**Pull request by P3tray**
Version 1 of the Windows XP theme.

Might update it when I get bored again.

[Image of what it looks like](https://cdn.discordapp.com/attachments/195368921451331584/862323370287431680/unknown.png)

### CODE REVIEW

**Comment by LolloDev5123** [comment]
Windows XP is always Light theme inside, try rounding some things but also add a border around the edges? 
immagine

**Comment by LolloDev5123** [comment]
Yes I know that is linux but yeah hehe

**Comment by GalacticInspired** [comment]
image

**Comment by LolloDev5123** [comment]
Also might have issues with XP logo but idk or idc

**Comment by P3tray** [comment]
I'm aware of how XP really looks, but I can't be asked to modify the entire window configuration to account for this. YET.

Hence V1.

And the logo? You can pirate XP without anyone on the planet giving a shit. Not to mention this is not the first upload of the logo onto the site.

**Comment by Expertcoderz** [comment]
You gotta improve the 'speaker' title button on the audio player window (as well as countdown and alert UIs).

**Comment by P3tray** [comment]
> You gotta properly position the 'speaker' title button on the audio player window (as well as countdown and alert UIs).
> 

This is actually a bug in every theme besides Default and it's modifications. See rounded for reference on that, hence why I included the AP's screenshot to display the issue.

**Comment by Expertcoderz** [comment]
> > You gotta properly position the 'speaker' title button on the audio player window (as well as countdown and alert UIs).
> > 
> 
> This is actually a bug in every theme besides Default and it's modifications. See rounded for reference on that, hence why I included the AP's screenshot to display the issue.

Aero doesn't have this issue :D

**Comment by GalacticInspired** [comment]
ez fix

**Comment by Sceleratis** [comment]
Holy crap. Looking at the images of the old XP windows I just now realized the little dash in the minimize button is meant to represent the minimized window button thing on the task bar. gg.

**Comment by LolloDev5123** [comment]
> 
> 
> > > You gotta properly position the 'speaker' title button on the audio player window (as well as countdown and alert UIs).
> > > 
> > 
> > 
> > This is actually a bug in every theme besides Default and it's modifications. See rounded for reference on that, hence why I included the AP's screenshot to display the issue.
> 
> Aero doesn't have this issue :D
> 
> 
> But yes rounded is bugged and fixing it seems non-straightforward.

Neither does Unity :)

**Comment by P3tray** [comment]
> 
> 
> > > > You gotta properly position the 'speaker' title button on the audio player window (as well as countdown and alert UIs).
> > > > 
> > > 
> > > 
> > > This is actually a bug in every theme besides Default and it's modifications. See rounded for reference on that, hence why I included the AP's screenshot to display the issue.
> > 
> > 
> > Aero doesn't have this issue :D
> > 
> > But yes rounded is bugged and fixing it seems non-straightforward.
> 
> Neither does Unity :)

Great for you guys...

**Pull request merged**
