### PR TITLE
Optimised and improved code

### PR DESCRIPTION
**Pull request by ccuser44**
Optimised and shortened CreateSoundPart code

### CODE REVIEW

**Comment by Sceleratis** [comment]
Listed as draft. Not mergable (?)

**Comment by ccuser44** [comment]
Well yes the pull is not ready i'll make it mergable when it is.

**Comment by Sceleratis** [comment]
I apologize deeply.

**Comment by ccuser44** [comment]
It is conflicting. I have to remake this someday.

**Pull request closed without merging**
