### PR TITLE
Added optional ban reason to :ban and :gameban

### PR DESCRIPTION
**Pull request by Awesomewebm**

### CODE REVIEW

**Comment by moo1210** [comment]
Kinda defeats the point, only shows on the first disconnect, not retrys

**Comment by Awesomewebm** [comment]
> Kinda defeats the point, only shows on the first disconnect, not retrys

Don’t worry, I can find a way to make bans have reasons attached with them, to actually make it useful

**Comment by Awesomewebm** [comment]
Gonna rethink this one

**Comment by Sceleratis** [comment]
O. Ok.

**Pull request closed without merging**
