### PR TITLE
Removed LockLighting

### PR DESCRIPTION
**Pull request by ccuser44**
#290 didn't renove all FD spesific code. For example there was LockLighting left. Also LockLighting wasn't used as it was replaced by locallighting.
Also there might be other FD spesific code but I am too lazy 2 check 4 them.

### CODE REVIEW

**Comment by Sceleratis** [comment]
LockLighting isn't related to FE pretty sure, it's just trying to prevent/detect local client lighting changes or something like that

**Comment by ccuser44** [comment]
There is a comment saying --// Replaced by LocalLighting
and localLighting was removed in the FD spesific code removal pull.
Also it seems that LockLighting doesn't log if the client changes the lighting.

**Comment by Sceleratis** [comment]
rip

**Comment by pacucci** [comment]
> rip

Take a look at my pull request yes???

**Pull request merged**
