### PR TITLE
Communications Centre & Notifications update.

### PR DESCRIPTION
**Pull request by P3tray**
!nh and similar aliases exist

Notifications look better, function way better, and function using ScrollingFrames.

Commiting to only the default theme because of conflicts in *some* other themes (You cannot tween a frames position under the influence of UIListLayout).

Bad screenshot provided

image

<3

### CODE REVIEW

**Comment by Sceleratis** [comment]
Nicu

**Comment by P3tray** [comment]
> Nicu

Nicu

**Comment by GalacticInspired** [comment]
Center

**Comment by LolloDev5123** [comment]
Maybe let's make non-important notifications disappear after a while, but still be accessible AND clickable from the Notifications Center (not centre)

**Comment by GalacticInspired** [comment]
Center!!!!

**Comment by P3tray** [comment]
> Maybe let's make non-important notifications disappear after a while, but still be accessible AND clickable from the Notifications Center (not centre) AND maybe stuff like this could be accessed from the **user**panel?

Have you tried this PR? This is exactly what it does... The already existing behaviour has not (really) changed.

**Comment by P3tray** [comment]
funny fishies

**Pull request merged**
