### PR TITLE
ADD OBAMA

### PR DESCRIPTION
**Pull request by pbstFusion**
obama is the best. he needs a command.

### CODE REVIEW

**Comment by EnderUwU** [comment]
Ok

**Comment by moo1210** [comment]
The command isn't set up correctly. Nor do I personally see any use for a command that just plays a sound, just use :music

**Comment by pbstFusion** [comment]
> The command isn't set up correctly. Nor do I personally see any use for a command that just plays a sound, just use :music

ok boomer

**Comment by Sceleratis** [comment]
an obama command feels like a good way to somehow get banned because someone somewhere will interpret it poorly 😒

**Comment by Sceleratis** [comment]
alllsssooo the function isn't valod and you didn't change the original settings after you copy-pasted the sceleratis command (so the command is still :sceleratis)

**Pull request closed without merging**
