### PR TITLE
Added 4 commands back, that allow you to change clothings and face with images as well.

### PR DESCRIPTION
**Pull request by karl-police**
Added 4 commands back, that allow you to change shirt, pants, face and tshirt with images as well.

They're named "customshirt, custompants, customtshirt, customface", they all allow the player running the command to specifiy image IDs as well.

### CODE REVIEW

**Comment by joritochip** [comment]
If decals are supported as faces in :avataritem then we could probably go without adding :customface

**Comment by karl-police** [comment]
> If we add decal support as faces in :avataritem then we could probably go without adding :customface

You need to add a second argument for, face, shirt, pants and etc. for custom stuff, then it could only work.

**Comment by joritochip** [comment]
> > If we add decal support as faces in :avataritem then we could probably go without adding :customface
> 
> You need to add a second argument for, face, shirt, pants and etc. for custom stuff, then it could only work.

Custom shirt/pants/tshirt should probably still be separate, I was just talking about custom faces. We wouldn't need a second argument if we assume all decals should be applied as faces

**Comment by joritochip** [comment]
> Custom shirt/pants/tshirt should probably still be separate, I was just talking about custom faces. We wouldn't need a second argument if we assume all decals should be applied as faces

Nevermind, this won't work the way I thought it would.

**Review by ccuser44 — CHANGES_REQUESTED** [review]
I think this should only be used for the images.
ie. these custom commands should only have the abbility to change the image asset id.

So I don't think we'd need to have the support for assets other than images in the custom commands.

**Comment by karl-police** [comment]
> I think this should only be used for the images. ie. these custom commands should only have the abbility to change the image asset id.
> 
> So I don't think we'd need to have the support for assets other than images in the custom commands.

but if they don't have a shirt they need a shirt to get the image

**Comment by ccuser44** [comment]
> > I think this should only be used for the images. ie. these custom commands should only have the abbility to change the image asset id.
> > So I don't think we'd need to have the support for assets other than images in the custom commands.
> 
> but if they don't have a shirt they need a shirt to get the image

There are already commands for that

**Comment by karl-police** [comment]
> > > I think this should only be used for the images. ie. these custom commands should only have the abbility to change the image asset id.
> > > So I don't think we'd need to have the support for assets other than images in the custom commands.
> > 
> > 
> > but if they don't have a shirt they need a shirt to get the image
> 
> There are already commands for that

which ones? I really wonder

**Comment by pbstFusion** [comment]
When merge/cancelled???

**Pull request merged**
