### PR TITLE
Add ability to change HelpButtonImage from loader

### PR DESCRIPTION
**Pull request by pbstFusion**
I FINALLY LEARNED HOW TO DO TWO COMMITS IN ONE REQUEST!
Based on skyy's change but not taken from it

### CODE REVIEW

**Review by ccuser44 — APPROVED** [review]

**Comment by pbstFusion** [comment]
yos

**Comment by p3tray** [comment]
yes

**Comment by Sceleratis** [comment]
have you confirmed this actually works considering you aren't grabbing the HelpButton setting from the server anywhere?

**Comment by pbstFusion** [comment]
eh?

**Comment by GalacticInspired** [comment]
hello god Davey_Bones.

**Comment by GalacticInspired** [comment]
<@81901953285623808>
get pinged

**Comment by LolloDev5123** [comment]
Smol problem, the default setting needs to be changed too, if someone is using an old loader without the setting in the loader but with a new module then the helpbutton will not display altogether

**Comment by pbstFusion** [comment]
yes you are le idot

**Comment by SimTheProtogen** [comment]
why

**Pull request merged**
