### PR TITLE
Added filter to :makeserver.

### PR DESCRIPTION
**Pull request by DavidsBaszucki**
Chat must be filtered or your model will face moderation.

### CODE REVIEW

**Comment by GalacticInspired** [comment]
i hate u ceo

**Comment by DavidsBaszucki** [comment]
cope

**Comment by joritochip** [comment]
Pretty sure the first argument would already be filtered due to the `Filter = true` on the command. I'll have to test this later.

**Comment by DaEnder** [comment]
it wasnt

**Comment by joritochip** [comment]
> it wasnt

I just tested it out and it does in fact filter already. Are you sure you were testing in a live server? Filtering does not work in Studio/play solo.

**Pull request closed without merging**
