### PR TITLE
Lots of new features

### PR DESCRIPTION
**Pull request by imskyyc**
*taps clipboard*
Alright so, a looooooooooot of things were changed around here.
Settings: Added support for custom Kick messages (Ban, Trelloban, TimeBan, GameBan, Slock, and Whitelist)
API: Changed it to just link back to the GitHub wiki, since all of that stuff was mostly outdated.
Loader: Rescripted it so it looks **a bit** cleaner
HelpButton: Added option to customize the HelpButton
Message: Added the ability to set a custom SystemMessage Image for the `:sm` command, which shows up below the title
Modified the server to support the new Loader
Modified the UpdateData function to (not break) work better
Updated the Functions module to support the new Kick messages

**REWROTE THE TRELLO API**
The Adonis TrelloAPI now supports PUT/DELETE requests, and the entire system has been fixed to support it.
F3X Deps were updated to not spam the Script Analysis tool with a trillion warnings
Added classic Open-Source Kronos' tracking dependencies
Updated the Remote modules
Functions:
MakeGuiGet (Used for Votes and YesNoPrompt)
GetGui (Used for checking if a player has a specific GUI on their screen)

(first version of this i accidentally submitted, oops)

Updated the Fly script to support using `R` and `F` to increase / decrease flight speed.
Aaand that's about it.

### CODE REVIEW

**Comment by TheCoolOne123** [comment]
Holy mother of shirtballs, how long have you worked on this.

**Comment by Awesomewebm** [comment]
This will make 1 really long changelog

**Comment by TheLegendarySpark** [comment]
Great! I was wondering about adding this to to your or -> ``Process.PlayerAdded``. It'll be beneficial to have banned players see their ban message, duration, and reason:

```
PlayerAdded = function(p)
		if p.UserId < 0 and p.Name:match("^Guest ") and not service.RunService:IsStudio() then
			p:Kick("Guest Account")
		elseif Anti.UserSpoofCheck(p) then
			Anti.Detected(p, "kick", "Username Spoofing");
		else
			local key = tostring(p.userId)
			local keyData = {
				Player = p;
				Key = Functions:GetRandom(); 
				Decoy1 = Functions:GetRandom();
				Decoy2 = Functions:GetRandom();
				Cache = {};				
				Sent = 0;
				Received = 0;
				LastUpdate = tick();
				FinishedLoading = false;
				LoadingStatus = "WAITING_FOR_KEY";
			}

			Remote.PlayerData[key] = nil
			Remote.Clients[key] = keyData

			spawn(function()
				local playerGui = p:FindFirstChildOfClass("PlayerGui") or p:WaitForChild("PlayerGui", 600);
				if playerGui then
					playerGui.Changed:Connect(function()
						if playerGui.Name ~= "PlayerGui" then
							playerGui.Name = "PlayerGui";
						end
					end)
				end
			end)

			local PlayerData = Core.GetPlayer(p)
			local level = Admin.GetLevel(p)
			local banned = Admin.CheckBan(p)
			local removed = false

			--p:SetSpecial("Kick", Anti.RemovePlayer)
			--p:SetSpecial("Detected", Anti.Detected)
			Core.UpdateConnection(p)

			if banned then 
				
				removed = true
			end

			if Variables.ServerLock and level < 1 and not removed then
				local banData = Admin.GetBanData(p)
				
				if banData and banData.kickType == "GAME" then
					p:Kick("You are PERMANENTLY BANNED from the game\n \nReason: "..tostring(banData.reason).."\n \nDuration: INFINITE")
				elseif banData and banData.kickType == "BAN" then
					p:Kick("You are SERVER BANNED from this server\n \nReason: "..tostring(banData.reason).."\n \nDuration: INFINITE")
				elseif banData and banData.kickType == "TIME" then
					p:Kick("You are TEMPORARILY BANNED from the game\n \nReason: "..tostring(banData.reason).."\n \nDUE: "..tostring(Functions.EpochToHuman(banData.expireTime)))
				else
					p:Kick(Variables.LockMessage)
				end
				
				removed = true
			end

			if Variables.Whitelist.Enabled and not removed then
				local listed = false
				for ind, admin in next,Variables.Whitelist.List do
					if Admin.DoCheck(p,admin) then
						listed = true
					end
				end
				if not listed and level == 0 then
					p:Kick(Variables.LockMessage)
					removed = true
				end
			end

			if not removed then
				if Remote.Clients[key] then
					if not Anti.RLocked(p) then
						Core.HookClient(p)
						Logs.AddLog(Logs.Script,{
							Text = tostring(p).." joined";
							Desc = tostring(p).." successfully joined the server";
							Player = p;
						})

						p.CharacterAdded:Connect(function(c)
							service.TrackTask(tostring(p)..": CharacterAdded", Process.CharacterAdded, p)
						end)

						wait(60*10)
						if p.Parent and keyData and keyData.LoadingStatus ~= "READY" then
							Logs.AddLog("Script", {
								Text = tostring(p).." Failed to Load", 
								Desc = tostring(keyData.LoadingStatus)..": Client failed to load in time (10 minutes?)",
								Player = p;
							});
							--Anti.Detected(p, "kick", "Client failed to load in time (10 minutes?)");
						end
					else
						Anti.Detected(p, "kick", "Roblox Locked")
					end
				else
					pcall(function() p:Kick("Loading Error [Missing player, keys, or removed]") end)
				end
			end
		end
	end;
```

**Comment by Sceleratis** [comment]
Loader & Module IDs are incorrect

**Comment by TheLegendarySpark** [comment]
Actually, the PlayerAdded event whenever the player is banned, I didn't use GetKickMessage from the Functions, but it's fine if you want to use Function.GetKickMessage.

**Comment by NNickey** [comment]
> Loader & Module IDs are incorrect

They do point to your new profile and aren't shady group ones.
Unless you intend to keep the latest updated one on that account as a throwaway measure.

**Comment by imskyyc** [comment]
> Great! I was wondering about adding this to to your or -> `Process.PlayerAdded`. It'll be beneficial to have banned players see their ban message, duration, and reason:
> 
> ```
> PlayerAdded = function(p)
> 		if p.UserId < 0 and p.Name:match("^Guest ") and not service.RunService:IsStudio() then
> 			p:Kick("Guest Account")
> 		elseif Anti.UserSpoofCheck(p) then
> 			Anti.Detected(p, "kick", "Username Spoofing");
> 		else
> 			local key = tostring(p.userId)
> 			local keyData = {
> 				Player = p;
> 				Key = Functions:GetRandom(); 
> 				Decoy1 = Functions:GetRandom();
> 				Decoy2 = Functions:GetRandom();
> 				Cache = {};				
> 				Sent = 0;
> 				Received = 0;
> 				LastUpdate = tick();
> 				FinishedLoading = false;
> 				LoadingStatus = "WAITING_FOR_KEY";
> 			}
> 
> 			Remote.PlayerData[key] = nil
> 			Remote.Clients[key] = keyData
> 
> 			spawn(function()
> 				local playerGui = p:FindFirstChildOfClass("PlayerGui") or p:WaitForChild("PlayerGui", 600);
> 				if playerGui then
> 					playerGui.Changed:Connect(function()
> 						if playerGui.Name ~= "PlayerGui" then
> 							playerGui.Name = "PlayerGui";
> 						end
> 					end)
> 				end
> 			end)
> 
> 			local PlayerData = Core.GetPlayer(p)
> 			local level = Admin.GetLevel(p)
> 			local banned = Admin.CheckBan(p)
> 			local removed = false
> 
> 			--p:SetSpecial("Kick", Anti.RemovePlayer)
> 			--p:SetSpecial("Detected", Anti.Detected)
> 			Core.UpdateConnection(p)
> 
> 			if banned then 
> 				local banData = Admin.GetBanData(p)
> 				
> 				if banData and banData.kickType == "GAME" then
> 					p:Kick("You are PERMANENTLY BANNED from the game\n \nReason: "..tostring(banData.reason).."\n \nDuration: INFINITE")
> 				elseif banData and banData.kickType == "BAN" then
> 					p:Kick("You are SERVER BANNED from this server\n \nReason: "..tostring(banData.reason).."\n \nDuration: INFINITE")
> 				elseif banData and banData.kickType == "TIME" then
> 					p:Kick("You are TEMPORARILY BANNED from the game\n \nReason: "..tostring(banData.reason).."\n \nDUE: "..tostring(Functions.EpochToHuman(banData.expireTime)))
> 				else
> 					p:Kick(Variables.BanMessage)
> 				end
> 
> 				removed = true
> 			end
> 
> 			if Variables.ServerLock and level < 1 and not removed then
> 				p:Kick(Variables.LockMessage)
> 				removed = true
> 			end
> 
> 			if Variables.Whitelist.Enabled and not removed then
> 				local listed = false
> 				for ind, admin in next,Variables.Whitelist.List do
> 					if Admin.DoCheck(p,admin) then
> 						listed = true
> 					end
> 				end
> 				if not listed and level == 0 then
> 					p:Kick(Variables.LockMessage)
> 					removed = true
> 				end
> 			end
> 
> 			if not removed then
> 				if Remote.Clients[key] then
> 					if not Anti.RLocked(p) then
> 						Core.HookClient(p)
> 						Logs.AddLog(Logs.Script,{
> 							Text = tostring(p).." joined";
> 							Desc = tostring(p).." successfully joined the server";
> 							Player = p;
> 						})
> 
> 						p.CharacterAdded:Connect(function(c)
> 							service.TrackTask(tostring(p)..": CharacterAdded", Process.CharacterAdded, p)
> 						end)
> 
> 						wait(60*10)
> 						if p.Parent and keyData and keyData.LoadingStatus ~= "READY" then
> 							Logs.AddLog("Script", {
> 								Text = tostring(p).." Failed to Load", 
> 								Desc = tostring(keyData.LoadingStatus)..": Client failed to load in time (10 minutes?)",
> 								Player = p;
> 							});
> 							--Anti.Detected(p, "kick", "Client failed to load in time (10 minutes?)");
> 						end
> 					else
> 						Anti.Detected(p, "kick", "Roblox Locked")
> 					end
> 				else
> 					pcall(function() p:Kick("Loading Error [Missing player, keys, or removed]") end)
> 				end
> 			end
> 		end
> 	end;
> ```

That's all configurable in the Settings

**Comment by imskyyc** [comment]
> Loader & Module IDs are incorrect

I was originally making this update for my remade Kronos, which is why some of the things point to a random module or a lot of stuff is deleted. It **should** all be fixed, but I'll double check real quick

**Comment by imskyyc** [comment]
MainModule and LoaderIDs should be correct, according to https://github.com/Sceleratis/Adonis/pull/274/commits/f26bc867b35c44189f95137838b9efcf8825abbd

**Comment by TheLegendarySpark** [comment]
Do not merge! The logs module is broken. If this pr merges, the rest of Adonis is broken. Btw, why is the Logs module acting like the Variables module?

**Comment by TheLegendarySpark** [comment]
There's a code in Server.Lua that causes this error:
``invalid argument #1 to 'concat' (table expected, got string)``

```
        server.Variables.Messages.Ban = table.concat(server.Settings.BanMessage,"\n")
	server.Variables.Messages.TrelloBan = table.concat(server.Settings.TrelloBanMessage,"\n")
	server.Variables.Messages.TimeBan = table.concat(server.Settings.TimeBanMessage,"\n")
	server.Variables.Messages.GameBan = table.concat(server.Settings.GameBanMessage,"\n")
	server.Variables.Messages.Lock = table.concat(server.Settings.LockMessage,"\n")
	server.Variables.Messages.Whitelist = table.concat(server.Settings.NotWhitelistedMessage,"\n")
```

**Comment by TheLegendarySpark** [comment]
And one more thing, there's an error in the new loader:
``Configuration is not a valid member of Model "LOADER_FULLNAME"``

```local Config = Model.Configuration``` must changed to ```local Config = Model.Config``` via Loader.lua

**Comment by TheLegendarySpark** [comment]
> There's a code in Server.Lua that causes this error:
> `invalid argument #1 to 'concat' (table expected, got string)`
> 
> ```
>         server.Variables.Messages.Ban = table.concat(server.Settings.BanMessage,"\n")
> 	server.Variables.Messages.TrelloBan = table.concat(server.Settings.TrelloBanMessage,"\n")
> 	server.Variables.Messages.TimeBan = table.concat(server.Settings.TimeBanMessage,"\n")
> 	server.Variables.Messages.GameBan = table.concat(server.Settings.GameBanMessage,"\n")
> 	server.Variables.Messages.Lock = table.concat(server.Settings.LockMessage,"\n")
> 	server.Variables.Messages.Whitelist = table.concat(server.Settings.NotWhitelistedMessage,"\n")
> ```

Nevermind this. I realized what I've done wrong.

**Comment by Awesomewebm** [comment]
What’s causing the “conflicts” with the commands script, I can’t see why there’s conflicts

**Comment by Sceleratis** [comment]
The variables.lua conflict was easy to resolve, but the commands one is a bit more complex....

**Comment by Sceleratis** [comment]
clooossssin for now but hopefully this will see the light of day eventually when conflicts decide to stop conflicting

**Comment by Awesomewebm** [comment]
The conflict was that the fork still had the commands all in one module, and the current version has the commands divided up into modules. That would explain the conflict

**Comment by Sceleratis** [comment]
> The conflict was that the fork still had the commands all in one module, and the current version has the commands divided up into modules.

That wasn't the original issue. I made that comment before all the command changes. For whatever reason the original pull req was merging files incorrectly (parts of one command attached to parts of different commands for example)

**Comment by Awesomewebm** [comment]
> > That wasn't the original issue. I made that comment before all the command changes. For whatever reason the original pull req was merging files incorrectly (parts of one command attached to parts of different commands for example)

Likely a GitHub issue then. Understood

**Comment by Sceleratis** [comment]
Scoopyadoopadity sky come backity whackity yo slapity.

**Comment by pbstFusion** [comment]
i am gonna gradually implement stuff from this if nobody else does

**Comment by Dimenpsyonal** [comment]
Hmmm I think I shall add these changes

**Pull request closed without merging**
