### PR TITLE
Automatic deployment for main module

### PR DESCRIPTION
**Pull request by joritochip**
Requires a ROBLOSECURITY cookie of an alt account with model publishing permissions to go into the repository secrets with the name `ROBLOSECURITY`.

Automatically deploys MainModule to the Roblox model when a release is published. **Does not automatically deploy loader** since it would be tricky to do without setting DebugMode to false by default (edit: loader deployment in #503)

### CODE REVIEW

**Comment by LolloDev5123** [comment]
Would it be possible to also edit the MainModule's Version NumberValue? I'd say increment patch for every commit, and we would keep 229 as 2.2.9, but it would still be displayed as 229

**Comment by jaydensar** [comment]
maybe it should deploy when a release is created instead of on push

**Comment by joritochip** [comment]
> maybe it should deploy when a release is created instead of on push

Yeah this is a better idea actually, also gets rid of need for release branch

**Comment by Sceleratis** [comment]
> maybe it should deploy when a release is created instead of on push

uh yeah.

**Comment by joritochip** [comment]
Closing in favor of #503

**Pull request closed without merging**
