### PR TITLE
Update `Functions.Notification` to use `server.MatIcons`, allow player command notifications to be disabled

### PR DESCRIPTION
**Pull request by alau740**
- Update `Functions.Notification` to use the icon system introduced in #533 
- Shortened some assert messages in `moderators.lua`
- Allows the player command notifications introduced in #513 to be disabled (set `settings.PlayerCommandFeedback` to `false`)
This was done due to the notifications getting spammy and not everyone wants to hear notification sounds whenever someone runs a command on them.

### CODE REVIEW

**Comment by P3tray** [comment]
100% approve of this commit. Very nice.

**Comment by alau740** [comment]
I disabled the notifications by default as they can get annoying (due to the number of pings someone might get, especially if an admin decided to spam these commands!).

I might change the notifications into hints as they don't make ping sounds whenever someone receives them and will be a lot less annoying to people if a place owner has enabled `settings.PlayerCommandFeedback`.

**Comment by joritochip** [comment]
I think the addition of this setting is great, but I'm not sure how I feel about switching all of the messages to hints rather than notifications.

**Comment by GalacticInspired** [comment]
> I disabled the notifications by default as they can get annoying (due to the number of pings someone might get, especially if an admin decided to spam these commands!).
> 
> I might change the notifications into hints as they don't make ping sounds whenever someone receives them and will be a lot less annoying to people if a place owner has enabled `settings.PlayerCommandFeedback`.

I do NOT approve of this.

**Comment by moo1210** [comment]
I approve of having these disabled by default. They get very annoying when commands are ran often for obvious things, which they all are.

**Comment by Sceleratis** [comment]
> I think the addition of this setting is great, but I'm not sure how I feel about switching all of the messages to hints rather than notifications.

This

**Comment by GalacticInspired** [comment]
No point in having notifications then

**Comment by alau740** [comment]
I ended up reverting the commit that changed the notifications into hints.

**Pull request merged**
