### PR TITLE
Commands that were defaulted with the ":" prefix will now listen to the prefix in the settings

### PR DESCRIPTION
**Pull request by GalacticInspired**

### CODE REVIEW

**Comment by joritochip** [comment]
I think this was intentional but it can probably be changed

**Comment by GalacticInspired** [comment]
wouldn’t make sense

joritochip ***@***.***> schrieb am Fr. 11. Feb. 2022 um 16:52:

**Comment by Expertcoderz** [comment]
Pretty sure there's a security/safety-related reason behind this, considering the nature of those commands (especially :terminal and :errorlogs, same with :debugloadstring, :debugtesterror, and others). They're sometimes necessary in debugging and perhaps emergency situations and thus should remain accessible as much as possible (even if the prefix is set to nil or "𒁣").

I've got an idea on how to settle this and will ~~hijack~~ edit your PR once I get onto my PC.

**Comment by LolloDev5123** [comment]
Galactic, Ich glaube, du bist Deutscher

**Comment by GalacticInspired** [comment]
> Galactic, Ich glaube, du bist Deutscher

what are you saying

**Comment by P3tray** [comment]
> Pretty sure there's a security/safety-related reason behind this, considering the nature of those commands (especially :terminal and :errorlogs, same with :debugloadstring, :debugtesterror, and others). They're sometimes necessary in debugging and perhaps certain emergency situations and thus should remain accessible as much as possible (even if settings.Prefix is set to nil or "𒁣").
> 
> I've got an idea on how to settle this and will ~hijack~ edit your PR once I get onto my PC.

ehehahaha making settings.Prefix "" and making the command names use settings.Prefix.."commandname" and ":commandname"

**Comment by moo1210** [comment]
> They're sometimes necessary in debugging and perhaps certain emergency situations and thus should remain accessible as much as possible (even if settings.Prefix is set to nil or "𒁣").
The command doesn't need to be secretly hidden. It is a creator-level command.

**Comment by Expertcoderz** [comment]
> > They're sometimes necessary in debugging and perhaps certain emergency situations and thus should remain accessible as much as possible (even if settings.Prefix is set to nil or "𒁣").
> 
> The command doesn't need to be secretly hidden. It is a creator-level command.

A bit confused here(?) We're not trying to hide anything.

**Comment by GalacticInspired** [comment]
> Pretty sure there's a security/safety-related reason behind this, considering the nature of those commands (especially :terminal and :errorlogs, same with :debugloadstring, :debugtesterror, and others). They're sometimes necessary in debugging and perhaps certain emergency situations and thus should remain accessible as much as possible (even if settings.Prefix is set to nil or "𒁣").
> 
> I've got an idea on how to settle this and will ~hijack~ edit your PR once I get onto my PC.

still waiting for the hijack

**Comment by Expertcoderz** [comment]
> > Pretty sure there's a security/safety-related reason behind this, considering the nature of those commands (especially :terminal and :errorlogs, same with :debugloadstring, :debugtesterror, and others). They're sometimes necessary in debugging and perhaps certain emergency situations and thus should remain accessible as much as possible (even if settings.Prefix is set to nil or "𒁣").
> > I've got an idea on how to settle this and will ~hijack~ edit your PR once I get onto my PC.
> 
> still waiting for the hijack

Hijacked (partially).

**Pull request merged**
