### PR TITLE
Fixed dex

### PR DESCRIPTION
**Pull request by Kw6m**
I'm pretty pissed as to how dex does not work so here is a fixed one. (Same one as the broken one just an actually working one)

### CODE REVIEW

**Comment by Sceleratis** [comment]
Though this isn't actually going to make it work correctly, as that requires adding stuff server-side in a way that's secure tho I have ideas

**Comment by Kw6m** [comment]
Right. I can probably think up *something*

**Comment by Kw6m** [comment]
right this adds a tiny bit of security and actually works mostly

**Comment by Sceleratis** [comment]
Going to merge this but dex as a whole and everything related to it is going to be moved off to its own plugin.

**Comment by Sceleratis** [comment]
Annnddd apparently this is kaborked so going to yoink the dark dex and make it work I guess

**Pull request merged**
