### PR TITLE
Dark DexV3 (source)

### PR DESCRIPTION
**Pull request by DrewBokman**
Tested, works. Was dark dex v3 for synapse originally but I modified it to work without synapse. Comment any issues and ill fix it ASAP, but I tested it and it should work well. Way better than the current outdated version of dex Adonis has atm.

### CODE REVIEW

**Comment by DrewBokman** [comment]
Wow this PR is messed up somehow, don't know how DimensionalFusion guys commit got here, anyways still should work fine.

**Comment by DrewBokman** [comment]
Btw it still has its “Synapse edition” and other credits related to that, so just let me know if i need to change any of that.

**Comment by pbstFusion** [comment]
ok then

**Comment by Sceleratis** [comment]
Yoinking the file and closing this since it's not mergable (I'm tossing Dex into it's own module/plugin anyway)

**Pull request closed without merging**
