### PR TITLE
Fix for helpbuttonimage on old loaders

### PR DESCRIPTION
**Pull request by pbstFusion**
i forgot ok

### CODE REVIEW

**Comment by p3tray** [comment]
yor a dummy

**Comment by pbstFusion** [comment]
no u :(((

**Comment by p3tray** [comment]
uno reverse card

**Comment by p3tray** [comment]
#git conversation house

**Comment by GalacticInspired** [comment]
ok

**Comment by GalacticInspired** [comment]
nice conversation

**Comment by p3tray** [comment]
it is

**Comment by pbstFusion** [comment]
**muaha**

**Comment by p3tray** [comment]
so hows your day going you 3

**Comment by GalacticInspired** [comment]
*farts*

Who farted?

**Comment by p3tray** [comment]
ew

**Comment by p3tray** [comment]
who farted

**Comment by GalacticInspired** [comment]
<a:ASAS_Blink:814058167238656031>

**Comment by p3tray** [comment]
didn't work

**Comment by p3tray** [comment]
😏

**Comment by p3tray** [comment]
🤣

**Comment by GalacticInspired** [comment]
<a:pepestroke:529400492132925460>

**Comment by p3tray** [comment]
:hole:                           :woman_cartwheeling: 


:golf:                                                       :manual_wheelchair: :man_golfing:

**Comment by pbstFusion** [comment]
### no

**Comment by p3tray** [comment]
yes

**Comment by GalacticInspired** [comment]
*loud fart*


WHOEVER IS FARTING OVER THE INTERCOM, SHUT UP AND GO TO THE TOILET

**Comment by p3tray** [comment]
**Ew**

**Comment by p3tray** [comment]
[https://www.youtube.com/watch?v=21GGIoRKHvo](url)

**Comment by GalacticInspired** [comment]
hi how me find command by admin leval

**Comment by GalacticInspired** [comment]
https://www.youtube.com/watch?v=g206kwbS1xo

**Comment by p3tray** [comment]
by using HD admin instead

**Comment by GalacticInspired** [comment]
don't make me puke
i don't want to be big momma

**Comment by p3tray** [comment]
[](http://grabify.no/notaurl)

**Comment by p3tray** [comment]
asd

**Comment by p3tray** [comment]
github removed it

**Comment by p3tray** [comment]
[hppt://grabify.no/lmaoboxfortnitehacks](url)

**Comment by p3tray** [comment]
image

**Comment by p3tray** [comment]
interesting.

**Comment by AdjacentPhalanx** [comment]
who farted?

**Comment by EnderUwU** [comment]
*loud fart*


WHOEVER IS FARTING OVER THE INTERCOM, SHUT UP AND GO TO THE TOILET

**Comment by EnderUwU** [comment]
<a:pepestroke:529400492132925460>

**Comment by GalacticInspired** [comment]
STOP FARTING

**Comment by GalacticInspired** [comment]
OH, <@534419428368973835>... WHO DARES TO FART OVER THE INTERCOM?

**Comment by EnderUwU** [comment]
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo

**Comment by GalacticInspired** [comment]
Wait, we are all talking about *someone* farting over the intercom...

Let's move this somewhere else. I think the guests are confused.

**Comment by p3tray** [comment]
simbuilder go away stinky

**Comment by p3tray** [comment]
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo

**Comment by AdjacentPhalanx** [comment]
the only stinky thing here is you

**Comment by p3tray** [comment]
a̢̧̧̛̲̦̠̼̘̹̖̞̦̠̟̠̳̝̱̩̗̼͇͖̼̬͉͕̭̥͕̘̖̬͇̻̘̱̼̫̥͓͊̀̿͂̅̍͂̾̓͆̿͒̒͊̓̌́̊̋͐͗̅͑̉́́̈́̿̅̓̂̇̑̿̅̎̐͋́͌̕͟͞͞ͅͅŝ̢̧̧̛̲̰͔̰̻̘̣͔͍̣̰̖͈͕̦̤̻̜͉̘͔̙͙̘̺͔̅̓̃̇̆́̐̒͒̍̃͑̆̀̔̃̀̄̽̑͌̂̅͒̋̑̀͒̚̚͟͢͜͟͢͢͝͡͝į̢̧̛͉͇̮̟͕̘̱̝̠̖͚̦̞̦̜̟̥͇̤̻̖̫̃̅̆̐̓̅͑́̾̀͆̓̅́͂̌̓̿̍̒̀̿̑̚̕͘͢͞͡ͅͅͅơ͈̣̮͉̪̣̠̤̬̫̹͖̟͚̗͔̩̜̝̪͓͎̦̮̍́̍̑͆̅͌̎͗̇͛̇͛̌̎͗̅̽͌͋̽͐̂̂̚͜͢d̡̧̡̡̨̛̯̯̟̮̬̗̱̤̺͚͈͈̯͖͎̣̻͉̹̙̤͍̻͕̗̳͙̜̱͗́̅͆̑̉̈́́̍̎̍̾̉͛̄͆̊̓̄̒̔̾̉̃͛̔̅̒͊̓͜͝͡͡͞͞͞͝ͅͅͅī̢̡̨̧̪̪̜̣̬͙̲̖͕͇̠̜̥̟͚̳̗̺̫͖̹̗͈̼̣̞̫͎̜̥̬̲̪̟̫͌̀̆͋̌̅͆̈̓̓͆̅̊̉̆̏͛̍̒́͌͗̉̄͂̾́̽̐̽̌̒̇̑̊̕̚̚̕͘͢͢͜͟͞͞ȁ̧̢̧̛̯̘̺̳̳͇̠͔̻̲̗̻̻̌̅̌̂̋̉́́͊̌̄̊̎̂͘ͅs̡̙͇̼̱͔̋͛̂̏̽͗̚͢ơ̢̨̧̧̧͉̖͎͓͇̣̫̹̜̲̠̣͓͇̖͇̞̲̩̘̩̣̪̥͍͊̀͐̊̾̊̊͛͆̈̑͌̋͛͂̆͆͆̆̂̾́̈̏͗̔̿͊̚͘͢͜͟͢͡͞͡͠ͅp̨̨̧̧̧̡̛̝͔̯̹͍̭͍̳̦̙̗̠͕̬̖̭̣͎̺̟̺̳̊̌͆̀̂͆̇̔̐̾̌̒͑̉̆̾́̀̃͊̔̄̀̚̕͘͡͡ͅḑ̨̢̨̛͎̹͎̪̮̟͕̖͙̮̲͎̣̗͖̤̪̟̼̺̞̳̰̺̩̜̩̮̈́̑̐̇̐́̐̎̇̍̾̓͒̈̿̎̍̈̈́̃̽͆̍̿͒̆̔́̄̑͑̿̚͘͢͢͢͝͠ͅͅi̢̢̫̱͕͚̤̦̥̿͊͗͋̆̏́͗͟͝͡ạ̧̧̛̤̖͙̰̤̩̤̳̲͈̞͙͔̞͓͖̤͇̜̰̩͍̝̠͖̝̝̄͛̐̄͐̔̇̍͒̔̎̈́͌̐͂̆͋́̇̌̀̀̀̓̏̈́͑̈͊̓̈̈́̿̆͘̚͢͟͟͟͢͢͟͡͝͝͡ͅͅͅͅp̢̛̲̤̹̟̙̜̞͈̺͉̙̤͖̩̼̘̥͈̰̲̞̲̭͆̓̑̒͒͌̾͂̃̊̀͂̔͑̏̽̈́̓̔̓͘̚͘̕͢͢͡ơ̧̡̧̢̝͍̱̠͕̺̳̣̣̹̗͇̞͙̥̬̣͈̙͍̞͚͇͈̦̥̤̼͓͇͔̹͉͇̮̗̄́̀̃̋̉̍̔̐̐̃͌͊̀̃̏̏̀̍͊́̊͋̔̔͑̊̓̓̏̀͋͑͌̐̉̆̚̚͜͢͟͡͠͝͞ͅs͍̟̫̼̫̻̱̀̅͛̾̀̄̀

**Comment by p3tray** [comment]
s̨̢̨̢̩̜̝͓̤̜̞͎͉͓͓̙͍̰͓͚̬̯̯̮̘̺̳̳͎͈͔͈͎͕͍̓̈̅͋̾͊̑͆̅́͌̑̏̑͒̏̉́͌͒́͗̄͛̑͛̀̃̓̊̾̔̆̀͒̿͜͡ͅi̯͖̣̺̜͓̥͚̬̰̩͉̬̩̩̥͍̟̫͎͎͗͊̇̀͊͛́̇̑̒̓̎̏̿̓̒̾̈͘̕͘͟͟͞͡m̢̢̢̡̢̛̛̫͔͚̻͈̜̤̟͉̱̣̙̺͕̥̼̞͉̝̟͈̠͍͈̤̱͈̞͔̙̬̼̱̗̳͉̫̞̰̏́̏͑͆̌́̈̽̿̉͆͒̍͊̔̇̀̾̀͒̇̏̀̂̆̇̑̓͛̋̓̾̌͗̾̔̅̏̆̿͘͘͘̚̕͟͢͜͟͠͠ͅͅb̮̼͎̝͎̊͑͋̓͛͢͠ư̡̡̢̝̭͉͚̤͉̥̜̞̣̙͓̬̇͋́̂̀̄͂̂͆̄̀̔̈̋̓̀͗̕͜͜͜i̡̢̳̯̗̹̖̖͈̤̠̣͔̮̖͙͌͑͛́͌͗̉̋̑̉̒́̌̂̆͘͢͝l̢̡͇͇̤͍̘̞͉̣̠̭͖̜̺͊͊͌̓̌͗͊̏̓́̃̊̍̈͟͝͝d̗̪̿͐ȩ̧̗͈̂̓̋̂̾͘͢͢ȓ̡̨̧̡̧̧̡̧̧̛̛̬̠̝̜̤̮̦̘͇͚̖̜͇͙̞͈͈͔̙̣̼̜̭͇͍̬̞͚̦̋̈̊́̓͆̽̅̓̈́͆̐͌́̐̓̉͂̃̇̉͒̎͛̔̒̏̌̆͒̏̀̋͘̕͟͟͟͠͡͡ ͔̻͎̺̥̈́̀͑̚͝s̛̛̼̥̠̬̝͖͆̋̿͂̂͟t̡̡̧̡̢̛̛͚͓̺̜̺̼͕̦̜̺̣͎̺̭͔̺̠̙̝̖̞̝̺͖̭̠̝̭̮̾̆́̑̄̓͋̾̓̊̓̉̉͛̊͗͑̂̀̇̽̆͊͑͂͛͐͒͂̉͑̌̓͘̕̚͜͢͟͜͜͝͝ͅi̧̧̡̨̲̩̦͉̦̤͈̼̩̹̖̞̼̖̦̤̱̪͔̝͉̙̜̠̠͙̮͚̥͓̇̎̑͋͂̈̅̔͐̊̈̂̎̈́͐̈̒̿̎͆͊̾͆̓̎̉̄̽͑̎̽̕͜͢͞͝͞͡n͚̯͆̒k̡̖̹̫͍̯̜͉̽̄̾̆̑̍̌͞y̳̤͑̋͢͡

**Comment by GalacticInspired** [comment]
guys,  what do the visitors think? WE ARE TALKING ON THE INTERCOM PUBLICALLY!

**Comment by p3tray** [comment]
hahaha funny intercom

**Comment by GalacticInspired** [comment]
GFX-transparent

**Comment by p3tray** [comment]
oh no he has a gun

**Comment by GalacticInspired** [comment]
-shoots-

**Comment by GalacticInspired** [comment]
you're dead

**Comment by GalacticInspired** [comment]
-shoots <@405151351904010240>-

**Comment by GalacticInspired** [comment]
Sorry visitors, we are very unprofessional! I know!

**Comment by GalacticInspired** [comment]
go listen to music
https://music.youtube.com/watch?v=0eBOqG72EpE&list=RDAMPLLM

**Comment by optimisticside** [comment]
This is such a chaotic pull request

**Comment by GalacticInspired** [comment]
agreed

**Comment by GalacticInspired** [comment]
image
lets bully him

**Comment by pbstFusion** [comment]
[intercom start time]
And he's quite a big bully and he's also one heck of a- oh the intercom's on, isn't it
they need to add a flashing button or something
[intercom end chime]

**Comment by pbstFusion** [comment]
request merge when

**Comment by AdjacentPhalanx** [comment]
haha funny intercom go brrrr

**Comment by GalacticInspired** [comment]
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞoo͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞoo͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞoo͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞoo͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo
o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞoo͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo══════ஜ۩۞۩ஜ═════o͜ﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞﱞo

**Comment by pbstFusion** [comment]
:a:gameing:740321567661097043>

**Comment by pbstFusion** [comment]
<a:gameing:740321567661097043>

**Comment by GalacticInspired** [comment]
<a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526><a:483384216189665288:486565297126506526>

**Comment by GalacticInspired** [comment]
pbstFusion is FAT 🥇 



:)

**Comment by GalacticInspired** [comment]
EEEEE




































EEEEE

**Comment by pbstFusion** [comment]
no u :((((

**Comment by AdjacentPhalanx** [comment]
*intercom noises*

**Comment by AdjacentPhalanx** [comment]
**OK**

**Comment by EnderUwU** [comment]
[an pogchamp adonis feature snek pek. its gonna change everything ](https://youtu.be/bxqLsrlakK8)

**Comment by p3tray** [comment]
you can't trick a trickster

**Comment by p3tray** [comment]
- [ asd ]

**Comment by pbstFusion** [comment]
nice try

**Comment by GalacticInspired** [comment]
Oh uhh, the intercom is on.

**Comment by Sceleratis** [comment]
WHAT THE HECK YALL

**Pull request merged**
