### PR TITLE
Remove FD-specific code and unused dependency

### PR DESCRIPTION
**Pull request by jaydensar**
This PR removes most of the cruft left over from when FE was able to be off, such as:
* Local lighting
* Replication logs
* Network owner logs
* Anti delete tool
* Anti delete
* Anti un anchor
* Anti billboard image
* Anti insert

and some other random bits of code that checked if FE was enabled or not, and did something only if it was disabled

this also removes the Parser dependency, which wasn't referenced anywhere in the code

### CODE REVIEW

**Review by ccuser44 — CHANGES_REQUESTED** [review]
You shoud keep AntiGod as it may still be valid.
Also you forget to remove
settings.AntiDeleteTool = false 
and
settings.AntiDelete = false

**Comment by AdjacentPhalanx** [comment]
haha funny intercom

eh?

**Comment by GalacticInspired** [comment]
no

**Review by ccuser44 — APPROVED** [review]

**Review by ccuser44 — COMMENTED** [review]
̶W̶a̶i̶t̶.̶ ̶W̶h̶y̶ ̶w̶a̶s̶ ̶p̶a̶r̶s̶e̶r̶ ̶r̶e̶m̶o̶v̶e̶d̶.̶ ̶W̶a̶s̶ ̶i̶t̶ ̶u̶n̶n̶e̶c̶e̶s̶s̶a̶r̶y̶?̶   But my question is what did the parser do?

**Comment by jaydensar** [comment]
Whoops, didn't mean to close this.

**Comment by Sceleratis** [comment]
I think parser was used for saving stuff in the datastore

**Pull request merged**
