### PR TITLE
Add :trelloban

### PR DESCRIPTION
**Pull request by TheCakeChicken**
:trelloban --- CHECKS FOR TRELLO CONFIG BEFORE ATTEMPTING TO RUN.
~~:trelloupdate --- Updates the Adonis lists (Admin, bans, mutes, music, etc...) from Trello.~~

### CODE REVIEW

**Comment by Sceleratis** [comment]
Trello already updates on a not too long interval tho (it's like once a minute or twice a minute I think?)

**Comment by TheCakeChicken** [comment]
yea but what if you add something to the music list and are too impatient to wait

**Comment by TheCakeChicken** [comment]
i added the command to a modified adonis once and found it very useful for quickly undoing bans or adding music list items, even if it does auto-update. besides, can't the auto update be disabled or modified, surely it'd be better to also offer a manual way of doing it, if a user configures the interval to be really long for whatever reason

**Comment by Cald-fan** [comment]
> Trello already updates on a not too long interval tho (it's like once a minute or twice a minute I think?)

doesnt it go along with the http setting auto set to 60

**Comment by TheCakeChicken** [comment]
yeah but they do? the trelloban command works fine in a plugin (JetEire uses it in a plugin) and :tupdate works fine in the commands module, not to mention that trelloban also works in the commands module

**Comment by NNickey** [comment]
Yeah, the commands work fine, you made it. But I don't see the specific purpose of it as Adonis already updates trello every 60 seconds. Sure, having it as a command to update the music list fast is ok, but are you really going to join 'every server' in less than 60 seconds, just to load a 'refresh trello' command, so the player can join your game? Or by it seems the purpose you're using it, it's probably best to just have it as a plugin, instead of a modified adonis. Adonis supports the use of 'plugins' and 'plugins' can make new commands easily, without having to take the MainModule and add one in.

**Comment by TheCakeChicken** [comment]
:tupdate command removed after everyone's said it's useless

**Comment by TheCakeChicken** [comment]
> Edit: but I don't believe the use of a 'trello update', seems to be a per game unique case. An admin could easily abuse HttpService rate limit by keybinding 'trello update' and spamming.

You make a valid point, hence I've removed it. It obviously does work better in scenarios where people have added it themselves because they directly need it.

**Pull request merged**
