### PR TITLE
Deletion of useless themes

### PR DESCRIPTION
**Pull request by LolloDev5123**
Removed 3 Themes:
```
Hydris
Transblack
Steampunk
``` 
**Might wanna revamp some special ones in the future, idk.**

### CODE REVIEW

**Comment by Sceleratis** [comment]
Removed themes will be included in the Adonis EXTRAS model included with each release (when 223 is live) for anyone who still wants them.

**Comment by Dimenpsyonal** [comment]
RIP steampunk theme

**Comment by watameln** [comment]
say gex

**Comment by EasternBloxxer** [comment]
We are so back

**Comment by Dimenpsyonal** [comment]
Take that, Lollo.

**Pull request merged**
