### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SashaSyshenko**

### CODE REVIEW

**Comment by GalacticInspired** [comment]
we are not changing settings to russian

**Comment by SashaSyshenko** [comment]
Well, it just me trying to figure out how pull requests works without reading instructions

**Comment by P3tray** [comment]
> Well, it just me trying to figure out how pull requests works without reading instructions

Real SashaSyshenko?

**Comment by P3tray** [comment]
> _ No description provided. _

Get a better datastore key. Make it longer and put fancy symbols in it.

Not that it really matters, but put some sort of effort into it.

**Pull request closed without merging**
