### PR TITLE
Integration of Material UI icons + !serverinfo UI

### PR DESCRIPTION
**Pull request by Expertcoderz**
Okay, here we go as usual...

- ### Server information now accessible by players (!serverinfo/!serverdetails)

Workspace tab as well as the two title buttons that open the game explorer and performance stats are seen by admins only.
Only admins can see the levels/ranks of people listed under the Players tab.

image
image
image
image

- ### Advanced server performance stats (:perfstats/:performancestats/:serverstats)
image

- ### Material icons for UI

Easily implement Material UI icons in Adonis by `server/client.MatIcons[name]`. We now have unique window icons and search bar icons. Here are a few examples:

image
image
image
image
image
image
image
image
image

~~- ### In-game icon gallery (!materialicons/!maticons)
This is terrible at the moment by my standards and will be refined.~~ USELESS THEREFORE REMOVED

### CODE REVIEW

**Comment by Sceleratis** [comment]
fancy but alas... conflicts qq

**Comment by Sceleratis** [comment]
It looks like the conflicts can be resolved via the normal web ui on GitHub. I was going to resolve them but I'm not 100% on what to remove or keep so when you get a chance just take a look and resolve those and I'll merge this in cuz looks hot

**Comment by Sceleratis** [comment]
conflicts doin dirty

**Comment by joritochip** [comment]
Also should still consider removing the icon list command. I can't think of any practical use of them in-game

**Comment by Expertcoderz** [comment]
I've practically abandoned/forgotten about this PR over the weeks but anyways...

- material icons list command removed
- I _may_ attempt to resolve the accumulated conflicts in these few days (no promises)

**Comment by Expertcoderz** [comment]
The conflicts have been resolved. And hope I didn't make any fatal mistake in the process.

**Pull request merged**
