### PR TITLE
Unity Theme

### PR DESCRIPTION
**Pull request by LolloDev5123**
yeah cool stuff
RobloxScreenShot20210517_221144247
RobloxScreenShot20210517_221238740

plz check for uncool stuff like outdated Code Module inside Window, (it has some things my theme needs)

### CODE REVIEW

**Comment by GalacticInspired** [comment]
image

**Comment by LolloDev5123** [comment]
do not care it looks good

**Comment by pbstFusion** [comment]
why do you hurt me in this way

**Comment by LolloDev5123** [comment]
synapse sex

**Comment by LolloDev5123** [comment]
just a custom window, notification and stuff

**Comment by LolloDev5123** [comment]
updated it

**Pull request merged**
