### PR TITLE
Update ServerInfo Command, HTTP.CheckHttp and RunCommandAsPlayer

### PR DESCRIPTION
**Pull request by fxeP1**
Used Players:GetPlayers() for Non-Admins/Admins instead of NetworkServer:GetChildren()

~~Replaced ON/OFF with bool strings to make it more fast~~ [REVERTED]
Removed ThirdPartySales (ROBLOX doesn't respect this afaik and was replaced with one inside Game Settings https://i.imgur.com/Fyo6Hzs.png)

Fixed RunCommandAsPlayer trying to get a unknown variable, which was supposed to be plr

Logs lines with only spaces were removed
Fixed Logs indenting on the ServerDetails function

HTTP.CheckHttp is more simplified

### CODE REVIEW

**Comment by LolloDev5123** [comment]
replacing [ON] [OFF] with [true] [false] doesn't make it more fast in terms of nanoseconds

**Comment by mewwo** [comment]
> replacing [ON] [OFF] with [true] [false] doesn't make it more fast in terms of nanoseconds

Actually `LOADK` is faster than `LOADBOOL`

Screenshot_1

**Comment by LolloDev5123** [comment]
[ON] [OFF] looks better than [true/false] and the speed isn't really noticeable

**Comment by fxeP1** [comment]
> [ON] [OFF] looks better than [true/false] and the speed isn't really noticeable

Yeah I'm going to revert from the bool values to [ON] and [OFF] again.

**Pull request merged**
