### PR TITLE
comms panel

### PR DESCRIPTION
**Pull request by pbstFusion**
ez fix nobody can argue against

### CODE REVIEW

**Comment by GalacticInspired** [comment]
GENIUS

**Comment by pbstFusion** [comment]
> GENIUS

I am, in many ways, a genius

**Comment by joritochip** [comment]
If you are going to change the title you should probably change the other references to "communications center" for consistency

**Comment by pbstFusion** [comment]
well, I was going to do that, but then I didn't know if anything else relied on something, and I didn't want to break it

**Comment by joritochip** [comment]
If you mean external things like plugins, I wouldn't worry cause I think (?) that the comms center is not on release branch yet anyways

**Comment by pbstFusion** [comment]
ok superceeded by #721

**Comment by pbstFusion** [comment]
closing, superceeded by #722

**Pull request closed without merging**
