### PR TITLE
Update Moderators.lua

### PR DESCRIPTION
**Pull request by DaEnder**
Added ban count thing.

### CODE REVIEW

**Comment by Smaltin** [comment]
Try this?
`Remote.MakeGui(plr, "List", {Title = "Ban List (" .. table.getn(tab) .. ")"; Tab = tab;})`

table.getn(table) returns the count of elements in the table

**Comment by DaEnder** [comment]
Ok

**Comment by pbstFusion** [comment]
ok but why do we need this

**Comment by DaEnder** [comment]
to see how many bans there are?

**Comment by rcmp168** [comment]
> to see how many bans there are?

This is already achievable by using ":banlist" command....

**Comment by Expertcoderz** [comment]
> > to see how many bans there are?
> 
> This is already achievable by using ":banlist" command....

But you'll have to count manually.

**Comment by GalacticInspired** [comment]
> 

Get counting

**Comment by GalacticInspired** [comment]
> > > to see how many bans there are?
> > 
> > 
> > This is already achievable by using ":banlist" command....
> 
> But you'll have to count manually.

Get counting

**Comment by LolloDev5123** [comment]
Start... NOW! 1.. 2.. 3..

**Comment by rcmp168** [comment]
> > > > to see how many bans there are?
> > > 
> > > 
> > > This is already achievable by using ":banlist" command....
> > 
> > 
> > But you'll have to count manually.
> 
> Get counting

I thought he wanted a list of banned users, i didnt know he wanted a COUNTER for bans

**Comment by Smaltin** [comment]
> > > > > to see how many bans there are?
> 
> > > > 
> 
> > > > 
> 
> > > > This is already achievable by using ":banlist" command....
> 
> > > 
> 
> > > 
> 
> > > But you'll have to count manually.
> 
> > 
> 
> > Get counting
> 
> 
> 
> I thought he wanted a list of banned users, i didnt know he wanted a COUNTER for bans

Clearly never checked the commit. 🤦‍♂️

**Pull request merged**
