### PR TITLE
Comms Panel

### PR DESCRIPTION
**Pull request by pbstFusion**
removed "center"

### CODE REVIEW

**Comment by GalacticInspired** [comment]
GENIUS

**Comment by GalacticInspired** [comment]
communication word need changing, how is it communitive?

**Comment by pbstFusion** [comment]
uhh... notification panel? notification history? maybe

**Comment by LolloDev5123** [comment]
How about Notifications

**Comment by GalacticInspired** [comment]
notification history, that sounds perfect!

**Comment by GalacticInspired** [comment]
it legit shows a history of notifications

**Comment by pbstFusion** [comment]
yes of course

**Comment by LolloDev5123** [comment]
"Notifications"

**Pull request merged**
