### PR TITLE
Better serverdetails and datetime command + :thru

### PR DESCRIPTION
**Pull request by LolloDev5123**
Better serverdetails

- The main serverdetail comamnd is now :serverinfo, much less confusing than the :details command
- Serverdetails now display [ON] and [OFF] instead of Enabled and Disabled
- Serverdetail field names now include spaces

Datetime command

The datetime command is a list command that returns os.date() values from os.time() in a table with formatting and easier understanding.

Thru command
A short alternative to the unofficial :to me that comes from the /thru in worldedit commands in minecraft that lets players pass through blocks.

upgrade12 (2)
upgrade12 (1)

### CODE REVIEW

**Comment by AdjacentPhalanx** [comment]
Funny intercom go brrrr

**Comment by SimTheProtogen** [comment]
e

**Comment by Sceleratis** [comment]
Thru's description states it lets you pass through objects and such, but to me this just looks like another version of :to so why not just add thru as an alias for :to instead?

**Comment by pacucci** [comment]
I stated that :thru is identical to :to me, it uses the :to me, it isn't made to teleport to someone

**Comment by pacucci** [comment]
It's basically identical but more practical

**Comment by pacucci** [comment]
Im thinking about adding a notification instead of an hint when sending a message, might do it in another pull request

**Comment by Sceleratis** [comment]
> I stated that :thru is identical to :to me, it uses the :to me, it isn't made to teleport to someone

yeah it just noticed the "me" part of that lol

**Comment by pacucci** [comment]
> > I stated that :thru is identical to :to me, it uses the :to me, it isn't made to teleport to someone
> 
> yeah it just noticed the "me" part of that lol

aight

**Comment by pacucci** [comment]
Also, maybe i'll do a pr, or if that's up to you, you can do it yourself, since Displaynames are rolling out, you could add a @ to things that display the .Name of a player, such as the pms, i also added a notification bit instead of the hint when someone pms

**Comment by SimTheProtogen** [comment]
cool

**Review by SimTheProtogen — COMMENTED** [review]
cool

**Comment by LolloDev5123** [comment]
shut

**Pull request merged**
