### PR TITLE
Update Credits.lua

### PR DESCRIPTION
**Pull request by c6lvnss**

### CODE REVIEW

**Comment by P3tray** [comment]
I approve these changes.

**Comment by P3tray** [comment]
I'm not sure why a 1st time contributor is litterally adding 2 names to the credits as their first commit but here we go.

**Comment by c6lvnss** [comment]
> I'm not sure why a 1st time contributor is litterally adding 2 names to the credits as their first commit but here we go.

When the credits tabs were made 2 additions and 1 modification to the credits list were missing. Reference to this [commit](https://github.com/Sceleratis/Adonis/blob/adabbbbc0fe46d853a5ee566766f35dc612a0129/MainModule/Server/Shared/Credits.lua).

**Comment by happyman090** [comment]
wait whats the point of this pull request

**Comment by Sceleratis** [comment]
> wait whats the point of this pull request
Some changes to the credits were apparently lost when the tabbed credit list commit was merged.

**Pull request merged**
