### PR TITLE
Fix Dance command R15 compatibility

### PR DESCRIPTION
**Pull request by chexburger**
Adds R15 compatibility for the dance command. #165

### CODE REVIEW

**Review by DavidBaszuckiA — CHANGES_REQUESTED** [review]
you forgot to add the Premium Adonis check to this. needs to be fixed ASAP else we cannot become rich.

**Comment by DaEnder** [comment]
now broken in R6 lol

**Comment by DaEnder** [comment]
might be some other pr breaking it idk

**Comment by chexburger** [comment]
> might be some other pr breaking it idk

My merge only changes which animation is called based on rig type. New issue must be further up the chain when the animation is ran.

**Pull request merged**
