### PR TITLE
Create a CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by pbstFusion**
Guide for contributing to Adonis

### CODE REVIEW

**Comment by Sceleratis** [comment]
Bruh this is just a template with some minor changes

**Comment by pbstFusion** [comment]
point still stands lol

**Comment by pbstFusion** [comment]
_Ok ive added real stuff_

**Comment by Sceleratis** [comment]
Code 👏 or 👏 wiki 👏 contributions 👏 

There was an attempt, but now I'm going to make a proper contributing file.

**Pull request closed without merging**
