### PR TITLE
Pban added

### PR DESCRIPTION
**Pull request by pbstFusion**
/shrug if i did a big dumb

### CODE REVIEW

**Review by ccuser44 — COMMENTED** [review]
Pban already exists. it is permenant ban

**Comment by pbstFusion** [comment]
i couldn't find it in files, can you tell me where

**Comment by p3tray** [comment]
wait you did that

**Comment by p3tray** [comment]
i though you made it a new command

**Comment by p3tray** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by p3tray** [comment]
wate of 5 mins

**Comment by p3tray** [comment]
waste

**Comment by pbstFusion** [comment]
ha

**Comment by pbstFusion** [comment]
you did epic fail

**Comment by happyman090** [comment]
As I said with the other pull request, adding pban as an alias to gameban is inappropriate because it is **not** permanent. Also, no need for permanent bans in the first place.

**Comment by pbstFusion** [comment]
gameban permanently bans someone from a game until unbanned, how is it not permanent

**Comment by happyman090** [comment]
Permanent means irreversible, does it not?

Gamebans are **indefinite**, not **permanent**, so calling them permanent is misleading because it's not permanent.

**Comment by pbstFusion** [comment]
Why does this affect the suggestion?

**Comment by pbstFusion** [comment]
Having a proper, full permanent ban is no help to pretty much anyone. Adding pban as an alias to gameban is more helpful than a proper permanent ban, as it can be done without resetting the datastores and wiping all other bans.

**Comment by happyman090** [comment]
> How does this affect the suggestion?

Because adding pban as an alias to gameban doesn't make sense. As I said, pban is not reflective of the behaviour of gameban, so it shouldn't be added as an alias of it.

> Having a proper, full permanent ban is no help to pretty much anyone. Adding pban as an alias to gameban is more helpful than a proper permanent ban, as it can be done without resetting the datastores and wiping all other bans.

I totally agree with you here and that's why pban shouldn't exist in the first place. There is no need to add pban because gameban suffices.

**Comment by Sceleratis** [comment]
> > Why does this affect the suggestion?
> 
> Because adding pban as an alias to gameban doesn't make sense. As I said, pban is not reflective of the behaviour of gameban, so it shouldn't be added as an alias of it.
> 
> > Having a proper, full permanent ban is no help to pretty much anyone. Adding pban as an alias to gameban is more helpful than a proper permanent ban, as it can be done without resetting the datastores and wiping all other bans.
> 
> I totally agree with you here and that's why pban shouldn't exist in the first place.

Going to just merge the other one that brings it in as an alias. I agree that it is unnecessary overall, but adding it as an alias isn't a huge deal especially since it won't show up in the commands list.

**Comment by pbstFusion** [comment]
mr scel, the pull requests are the same

**Comment by pbstFusion** [comment]
only mine was first >:|

**Comment by Sceleratis** [comment]
are they? I thought yours was adding a whole command wasn't it?

**Comment by Sceleratis** [comment]
I'll just give you both credit for it in the changelog lol

**Pull request closed without merging**
