### PR TITLE
PMLogs, Kronos Massbring & Thru (:to me alternative)

### PR DESCRIPTION
**Pull request by pacucci**
- Added PMLogs which work and log only if the required setting is enabled, which is disabled by default
- Added the Kronos massbring which brings multiple people without flinging in an orderly manner
- Added :thru which is an alternative to :to me that derives from the /thru command that minecraft world edit has

I hope this isn't outdated compared to other pull requests, take parts of this to adapt them to the main if this is majorly outdated.
Please tell me if something doesn't work
RobloxScreenShot20210305_010827506

### CODE REVIEW

**Comment by ccuser44** [comment]
I think you should just replace the default bring command rather than creating a new one.

**Comment by pacucci** [comment]
Alright! The thing is massbring is intended for more than 5 players, while bring is intended to teleport a player, maybe i will find a way to merge these

**Comment by NNickey** [comment]
Inconsistencies with updating moderators.lua

MassBring =
server.Commands.WisperLogs =

**Comment by NNickey** [comment]
I also do not see the PMLogs setting added to Default Settings?

If a user says a command on an outdated adonis settings, it'll error because default settings didn't come in to absorb a missing setting.

**Comment by pacucci** [comment]
Looking into it

**Comment by NNickey** [comment]
I wouldn't change the pm command to be a player prefix and leave it as default as users are already used to using Adonis with the command prefix on 'pms'

Your latest pull request for Update Moderators.lua just removed your addition of Thru, MassBring..

but for some reason removes...    Sparkles, Unsparkles, BlurEffect, BloomEffect, SunRaysEffect, ColorCorrectionsEffect, UnColorCorrection, UnSunRays, UnBloom, UnBlur, UnLightingEffect, ThermalVision, UnThermalVision, Piano, ClearGUIs, ResetLighting, ClearLighting, Freaky, Gear, Hat, Capes, Cape, UnCape, Slippery, UnSlippery, NoClip, GRPlaza...

ummmm

**Review by NNickey — CHANGES_REQUESTED** [review]
Some commands are being removed from this specific pull request unrelated to the pull request to update, decline.

**Comment by pacucci** [comment]
Oh no, I was updating these with my custom admin which removes fun commands, oops. The bring command is now merged with the massbring, if someone is willing to copy the important stuff for their own pull request, you can do that. NNickey, sorry im new. No need to be toxic.

**Comment by NNickey** [comment]
Not meaning to be toxic, just helping Scel from accidently merging an update that went unnoticed and broke release Adonis for a few minutes ❤️

**Pull request closed without merging**
