### PR TITLE
Add loader setting for whether Adonis' default music will appear

### PR DESCRIPTION
**Pull request by pbstFusion**
Here be Dragons

### CODE REVIEW

**Comment by P3tray** [comment]
pbst you do realise settings.music overwrites the default music or maybe im an idiot which is most likely

**Comment by pbstFusion** [comment]
you fool, settings.Music only appends the list!

**Comment by P3tray** [comment]
> you fool, settings.Music only appends the list!
image

**Comment by Sceleratis** [comment]
You didn't test this. What this is actually doing is making it so you *can't* use your own music.

**Comment by pbstFusion** [comment]
> You didn't test this.
Of course I didn't test this. What do you think I am, smart?

**Comment by pbstFusion** [comment]
+don't care + didn't ask + ratio

**Pull request closed without merging**
