### PR TITLE
Introducing !profile (replacement for :inspect)

### PR DESCRIPTION
**Pull request by Expertcoderz**
- It's now a player command usable for all at convenience.
- Includes an add friend/unfriend title button (not shown in the screenshot below since I'm viewing myself) and an inspect avatar title button.

image
### Privacy Mode setting for players
(The country/location code will be shown as '[Redacted]' on a player's profile if they have this setting enabled.)

image

### Searchability for friends & groups tabs
image
### More device info (Game tab is visible to admins only)
image

(Also, yes, I removed the Avatar tab from :inspect which was kinda useless.)

### CODE REVIEW

**Comment by LolloDev5123** [comment]
Why inspect is cool, it had way more data than what you're showing there

**Comment by Expertcoderz** [comment]
> Why inspect is cool, it had way more data than what you're showing there

Please explain.

**Comment by Expertcoderz** [comment]
About the avatar tab in the inspection interface, it was really just a waste of time and computing resources, even I cannot find curiosity to look at its info.

**Comment by LolloDev5123** [comment]
> 
> 
> > Why inspect is cool, it had way more data than what you're showing there
> 
> Please explain.

immagine
immagine
immagine

**Comment by Expertcoderz** [comment]
> > > Why inspect is cool, it had way more data than what you're showing there
> > 
> > 
> > Please explain.
> 
> immagine
> immagine
> immagine

1. If you look closely all the info from the original General tab exists on the new one plus the avatar thumbnail. In the new interface it'll show if the player being inspected is an Adonis contributor, Roblox admin and/or DevForum member.
2. Avatar tab including the avatar items list is still useless and replaced with the title button that opens Roblox's Avatar Inspect Menu.
3. All the stuff from the Adonis tab has been moved to the Game tab (visible to admins only) with the exception of Donor/Contributor status (moved to General) and Ban status (removed because useless).

**Comment by Expertcoderz** [comment]
> Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?
We can already tell by chat interactions.

**Comment by LolloDev5123** [comment]
> 
> 
> > Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?
> 
> We can already tell by interacting with them in chat. Privacy by obscurity...?

Alrighty, also, you should change some messages in "credentials", eg:
"Adonis Creator [Sceleratis/Davey_Bones]"
"Adonis Developer"
"Adonis Contributor (GitHub)"
"Adonis Donor"
"Roblox Employee/Staff"
"Devforum Member"

**Comment by Expertcoderz** [comment]
> > > Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?
> > 
> > 
> > We can already tell by interacting with them in chat. Privacy by obscurity...?
> 
> Alrighty, also, you should change some messages in "credentials", eg:
> "Adonis Creator [Sceleratis/Davey_Bones]"
> "Adonis Developer"
> "Adonis Contributor (GitHub)"
> "Adonis Donor"
> "Roblox Employee/Staff"
> "Devforum Member"

Done, thanks for suggesting.

**Comment by ccuser44** [comment]
> Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?

This might be againts Robloxes TOS and violate privacy laws. Possibly

**Comment by Sceleratis** [comment]
Tbh I like the idea of the avatar inspect as it allows you to see item names immediately in-game (though, I'd rather the names be on the right and the type on the left)

**Comment by Sceleratis** [comment]
> 
> 
> > Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?
> 
> This might be againts Robloxes TOS and violate privacy laws. Possibly

Might be good as an admin-only thing,

**Comment by Expertcoderz** [comment]
> > 
> > 
> > > Also, you should add Safe Chat to the Redacted Mode, since that's an easy way to tell if a kid is underage?
> > 
> > This might be againts Robloxes TOS and violate privacy laws. Possibly
> 
> Might be good as an admin-only thing, 

My reasoning behind making such info avaliable to general players is that **if anyone had admin perms in a game/their own game they wouldn't be prevented from seeing the info anyways**.

Furthermore, given how Roblox's text filtering aka. auto censorship system works, **it is already relatively easy to determine safe chat enabled ie. age group for any player who uses the chat for interaction.** For example, a method of doing so would be to enter something in the chat that would be filtered from the perspective of <13 players, then looking at the target's response.

Therefore, instead of privacy by obscurity I have instead opensourced the information to keep things clear and simple.

However, I do think that
- SafeChatEnabled should be hidden in Privacy Mode alongside Location/Country Code. I'll take care of this.
- Players should be more easily aware of Privacy Mode's existence. This could be achieved by a message in the Profile UI telling players how they can opt to hide their details.

**Comment by Expertcoderz** [comment]
Alright, SafeChatEnabled and Country/Location Code are now both hidden in Privacy Mode.

**Comment by happyman090** [comment]
Personally, I think it would be nice to readd the avatar tab functionality in some form by just adding a button somewhere in the profile tab which points to the [built-in avatar inspect menu](https://developer.roblox.com/en-us/articles/avatar-inspect-menu).

**Comment by Expertcoderz** [comment]
> Personally, I think it would be nice to readd the avatar tab functionality in some form by just adding a button somewhere in the profile tab which points to the [built-in avatar inspect menu](https://developer.roblox.com/en-us/articles/avatar-inspect-menu).

That's what I've already done with the title button.

**Comment by GalacticInspired** [comment]
Privacy mode should be enabled by DEFAULT.

**Comment by happyman090** [comment]
> > Personally, I think it would be nice to readd the avatar tab functionality in some form by just adding a button somewhere in the profile tab which points to the [built-in avatar inspect menu](https://developer.roblox.com/en-us/articles/avatar-inspect-menu).
> 
> That's what I've already done with the title button:
> 

Oops, my bad - did not see that.

**Comment by ccuser44** [comment]
> privacy by obscurity

I think you mixed up `security trough obscurity` and `privacy trough obscurity`.

Anyways relying on this behavior is hacky and it might change at any time.

Also I don't see what it helps to see if someone is a kid, and to be honest trying to knoen is kinda creepy.

Also it is still againts the TOS and _possibly_ illegal under privacy laws.

**Comment by Expertcoderz** [comment]
> I think you mixed up security trough obscurity and privacy trough obscurity.

I think not, for I made that phrasing up myself.

> Anyways relying on this behavior is hacky and it might change at any time.

Using the PolicyService API should be stable enough (much more so than test-filtering a string and looking at the result). I'l check if there's any better way.

> Also I don't see what it helps to see if someone is a kid, and to be honest trying to knoen is kinda creepy.

Ask those military game people. Also, it's already inferrable from they way they chat and Roblox's filtering methods. What is creepy is eventually finding out some other way. It's merely the general age group (<13 or 13+), anyways.

> Also it is still againts the TOS and possibly illegal under privacy laws.

You should have mentioned this months ago when the :inspect command was released. Anyways, I'm going read the ToS.

**Pull request merged**
