### PR TITLE
Remove Moderated/Copyrighted Audios from MusicList

### PR DESCRIPTION
**Pull request by Awesomewebm**
Many of the audios in the MusicList were either taken down for copyright or content deleted. They are unplayable and therefore unnecessary

### CODE REVIEW

**Comment by Sceleratis** [comment]
somehow has conflicts

**Comment by Awesomewebm** [comment]
Strange. It won’t let me correct it

**Comment by Awesomewebm** [comment]
For some reason it says there’s a conflict, even though there isn’t one. Just cut and paste this over the current musiclist

`MusicList = {
			{Name='jericho',ID=292340735};
			{Name='dieinafire',ID=242222291};
			{Name='beam',ID=165065112};
			{Name='myswamp',ID=166325648};
			{Name='skeletons',ID=168983825};
			{Name='russianmen',ID=173038059};
			{Name='freedom',ID=130760592};
			{Name='seatbelt',ID=135625718};
			{Name='tempest',ID=135554032};
			{Name="focus",ID=136786547};
			{Name="azylio",ID=137603138};
			{Name="caramell",ID=2303479};
			{Name="epic",ID=27697743};
			{Name="halo",ID=1034065};
			{Name="pokemon",ID=1372261};
			{Name="cursed",ID=1372257};
			{Name="extreme",ID=11420933};
			{Name="tacos",ID=142295308};
			{Name="wakemeup",ID=2599359802};
			{Name="awaken",ID=27697277};
			{Name="alone",ID=27697392};
			{Name="mario",ID=1280470};
			{Name="choir",ID=1372258};
			{Name="chrono",ID=1280463};
			{Name="dotr",ID=11420922};
			{Name="entertain",ID=27697267};
			{Name="fantasy",ID=1280473};
			{Name="final",ID=1280414};
			{Name="emblem",ID=1372259};
			{Name="flight",ID=27697719};
			{Name="gothic",ID=27697743};
			{Name="hiphop",ID=27697735};
			{Name="intro",ID=27697707};
			{Name="mule",ID=1077604};
			{Name="film",ID=27697713};
			{Name="nezz",ID=8610025};
			{Name="resist",ID=27697234};
			{Name="schala",ID=5985787};
			{Name="organ",ID=11231513};
			{Name="tunnel",ID=9650822};
			{Name="spanish",ID=5982975};
			{Name="venom",ID=1372262};
			{Name="wind",ID=1015394};
			{Name="guitar",ID=5986151};
			{Name="weapon",ID=142400410};
			{Name="derezzed",ID=142402620};
			{Name="sceptics",ID=153251489};
			{Name="pianoremix",ID=142407859};
			{Name="antidote",ID=145579822};
			{Name="overtime",ID=135037991};
			{Name="fluffyunicorns",ID=141444871};
			{Name="tsunami",ID=569900517};
			{Name="finalcountdownremix",ID=145162750};
			{Name="stereolove",ID=142318819};
			{Name='minecraftorchestral',ID=148900687}
			[Name='superbacon',ID=300872612}
		}; `

**Comment by Awesomewebm** [comment]
There was a typo with the formatting, I corrected it. Hopefully it will fix it

**Comment by Awesomewebm** [comment]
> somehow has conflicts

Should I redo the pull request, because it looks fine but somehow labels it a conflict

**Comment by Awesomewebm** [comment]
The conflict is due to the fact that the file hierarchy was changed, and my patch is outdated. I'm going to redo the pull request, and fix the issue

**Pull request closed without merging**
