### PR TITLE
Windows XP theme update

### PR DESCRIPTION
**Pull request by Expertcoderz**
still pretty bad tbh

image
image
image

### CODE REVIEW

**Comment by P3tray** [comment]
Getting closer, but still doesn't look close.

My condolances for trying.

**Comment by evanultra01** [comment]
i made a pull request for the winxp theme which fixes the gray background issue but i closed it because it looked terrible in my eyes

**Comment by Sceleratis** [comment]
I don't know if anyone actually remembers, but old Windows UI was disgusting.

**Comment by sea4h** [comment]
i love it best theme in adonis 10/10

**Pull request merged**
