### PR TITLE
Removed ability to ban yourself

### PR DESCRIPTION
**Pull request by crywink**

### CODE REVIEW

**Comment by Awesomewebm** [comment]
There's a conflict due to the changes in the file structure. Redo the pull request, editing the latest file, and the problem will be corrected

**Comment by NNickey** [comment]
This adds a lot more than just 'not being able to ban yourself anymore'.
💀

**Comment by crywink** [comment]
I'm actually not sure what happened to the file structure. I'll fix it when I get the chance.

**Comment by Sceleratis** [comment]
Bippity boppity boop

**Comment by Sceleratis** [comment]
memes

**Comment by joritochip** [comment]
This isn't an actual issue, as the command checks to see if the admin level of the person executing the command is *higher* than the admin level of the target. Since your admin level is not higher than your admin level, the command shouldn't run.

I guess a hint telling someone that they aren't allowed to ban themselves is a good idea, though.

**Comment by Awesomewebm** [comment]
Im gonna work on this and make a new pull request as this one won’t be fixed anytime soon

**Pull request closed without merging**
