### PR TITLE
Add icon to theme command

### PR DESCRIPTION
**Pull request by pbstFusion**
Why? Because I like it better. 
Palette chosen because colour indirectly ties in with "theme"

### CODE REVIEW

**Comment by pbstFusion** [comment]
Yes.

**Comment by pbstFusion** [comment]
add or else death

**Comment by P3tray** [comment]
Good contribution. I copy-pasted the notification code from elsewhere in Players.lua so feel free to add icons to them all. I dare you.

**Comment by pbstFusion** [comment]
> I copy-pasted the notification code from elsewhere in Players.lua so feel free to add icons to them all. I dare you.

Challenge accepted.

**Comment by P3tray** [comment]
> > I copy-pasted the notification code from elsewhere in Players.lua so feel free to add icons to them all. I dare you.
> 
> Challenge accepted.

Good. Good.

**Pull request merged**
