### PR TITLE
Improvements very well made here...

### PR DESCRIPTION
**Pull request by TheLegendarySpark**
> Added **Joined** for client datas
*I wanted to add this because it could help developers to retrieve information when the client joined the server*

> *Fixed Basic Admin message not properly showing longer messages*

> Added CustomRank check in ``Admin.DoCheck``

> Added a new UI 'Notifications' in Basic Admin theme as requested by #267 

> Fixed bugs from ``Admin.RunCommandAsPlayer`` preventing you from running a command as a player

> Fixed ``Admin.DoCheck`` returning an unusual error if you're targeting a non-existent player like ``Expected player in PlayerOwnsAsset()``

> Fixed Window not triggering the function ``OnClose`` (if listed) after pressing the Close button

### CODE REVIEW

**Comment by TheLegendarySpark** [comment]
This branch has a conflict with the file I added before. Wow.......

**Comment by Sceleratis** [comment]
CONFLICCCCTTTTSSS

**Comment by TheLegendarySpark** [comment]
> CONFLICCCCTTTTSSS

I reconstructed the Basic Admin. There shouldn't be any conflicts.

**Comment by Sceleratis** [comment]
ugh it won't even let me resolve them

**Comment by Sceleratis** [comment]
"too complex to resolve with the web editor" apparently so like wtf

**Comment by Sceleratis** [comment]
uh maybe try redoing without the basicadmin model and then just make a separate pull for the basicadmin theme stuff

**Pull request closed without merging**
